# Generated by Django 5.2.9 on 2025-12-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conmpany',
            new_name='Company',
        ),
    ]
