# Generated by Django 5.2.9 on 2025-12-02 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0002_rename_conmpany_company'),
        ('contacts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies_api.company'),
            preserve_default=False,
        ),
    ]
